Dasharo/open-source-firmware-validation

lib/dl-cache.robot
lib/power-after-fail-lib.robot

Use 15 seconds delay because if power is absent for less than roughly 10 seconds the platform powers on regardless of the settings (original firmware behaves the same) and waiting 10 seconds doesn't produce stable results.
Fixes https://github.com/Dasharo/dasharo-issues/issues/557.

lib/power-after-fail-lib.robot: wait 15 seconds before power on

---

dasharo-security/tpm2-commands.robot

TPM must not extend nor reset PCR values for PCRs 17-22 until it is in proper locality. This test checks if TPM correctly returns an error if such command is issued.

dasharo-security/tpm2-commands.robot: add test for locality protections

---

dasharo-performance/cpu-frequency.robot
lib/CPU-performance-lib.robot

Fix for this false failure:
```
CPF004.005 CPU with load runs on expected frequency (Ubuntu 22.04)... | FAIL |
Several failures occurred:
1) '4400.0 > 4400.0' should be true.
2) '400.0 < 400.0' should be true.
```
Also bump the number of threads in CPU stress test to actually load the CPU

Cpu freq fixes

---

.github/workflows/qemu-self-test.yml
scripts/ci/qemu-run.sh

Result with:
```
./scripts/ci/qemu-run.sh graphic os        
robot -L TRACE -v config:qemu -v rte_ip:127.0.0.1 -v snipeit:no dasharo-security/tpm2-commands.robot
==============================================================================
Tpm2-Commands                                                                 
==============================================================================
Checking if tpm2-tools is installed...
Package tpm2-tools is installed
TPMCMD001.001 Check if both SHA1 and SHA256 PCRs are enabled (Ubun... | PASS |
------------------------------------------------------------------------------
TPMCMD002.001 PCRREAD Function Verification (Ubuntu 22.04) :: This... | PASS |
------------------------------------------------------------------------------
TPMCMD003.001 …
```

Tpm support

---

dasharo-security/secure-boot.robot
lib/secure-boot-lib.robot

This tests whether we can enroll an outdated certificate, and run a `hello-world` program signed with it. So far it seems that thats possible.

Outdated certs test

---

dasharo-security/tpm2-commands.robot

Checks support of TPM for Sealing/Unsealing with additional policies (password, PCR and both at the same time)

dasharo-security/tpm2-commands.robot: add tests for file sealing with policies

---

dasharo-security/secure-boot.robot
lib/secure-boot-lib.robot

This test first generates keys in incorrect formats, then attemps to enroll them with sbctl tool, which should be impossible.

dasharo-security/secure-boot.robot: SBO009 added

---

dasharo-security/tpm2-commands.robot

The line that checks if the file was properly unsealed is missing. Right now the test only fails if [one of the previous commands fails](https://github.com/Dasharo/open-source-firmware-validation/blob/ami-encrypted-rootfs-tests/dasharo-security/tpm2-commands.robot#L233-L236).

dasharo-security/tpm2-commands.robot: added missing unseal check

---

dasharo-compatibility/setup-menu-information.robot
keywords.robot
lib/framework.robot
platform-configs/msi-pro-z690-a-ddr5.robot
platform-configs/msi-pro-z690-a-wifi-ddr4.robot
platform-configs/msi-pro-z790-p.robot
platform-configs/protectli-v1210.robot
platform-configs/protectli-v1410.robot
platform-configs/protectli-v1610.robot
platform-configs/protectli-vp2410.robot
platform-configs/protectli-vp2420.robot
platform-configs/protectli-vp4630.robot
platform-configs/protectli-vp4650.robot
platform-configs/protectli-vp4670.robot

Replaces: https://github.com/Dasharo/open-source-firmware-validation/pull/204
Results:
* QEMU:
```
==============================================================================
Setup-Menu-Information                                                        
==============================================================================
SET001.001 CPU clock speed displayed in setup menu :: This test ca... | PASS |
------------------------------------------------------------------------------
SET002.001 RAM speed displayed in setup menu :: This test case ver... | FAIL |
RAM speed not found
------------------------------------------------------------------------------
SET003.001 RAM size displayed in setup menu :: This test case veri... | PASS | …
```

Mem spd displayed v2

---

dasharo-performance/boot-time-measure.robot
lib/CPU-performance-lib.robot

Reboot should be called in each iteration, not at the end of the test. Fixes: https://github.com/Dasharo/open-source-firmware-validation/issues/238

Fix cbmem003.001

---

dasharo-compatibility/display-ports-and-lcd-support.robot
keywords.robot

right now all tests are assuming displays are connected to gpu `card0`, this is wrong on several levels:
- newer kernels start numbering at `card1`
- on multi-gpu systems this changes depending on driver load order
so find the right node by PCI device path. 00:02.0 is iGPU on Intel, probably won't work on AMD.
also, the dock tests try to find a specific DP output number, this is incorrect, as new connectors are created when a MST hub is connected and this will change pretty randomly. The hub may also work in SST mode and you'll need to check the toplevel port instead... it's complex. we should get the output list from the MST topology: `/sys/kernel/debug/dri/0/i915_dp_mst_info`
for example - 2 monitors connected via two MST hubs in series:
```
MST Source Port [ENCODER:253:DDI TC1/PHY TC1] …
```

Ncm mkc fixes

---

dasharo-security/me-neuter.robot
keywords.robot
lib/bios/menus.py
lib/options/dcu.robot
lib/options/uefi-setup-menu.robot
platform-configs/include/default.robot
platform-configs/include/novacustom-common.robot
scripts/check-unused-variables.sh

Introduce libraries for setting options. Tests will use one of these to configure options, and the actual mechanism (serial, DCU...) will be opaque.

Use DCU for UEFI settings on platforms w/o serial console

---

dasharo-compatibility/network-boot.robot

Added test to verify if network boot uses https:// and not http://
Fixes: [https://github.com/Dasharo/open-source-firmware-validation/issues/200](https://github.com/Dasharo/open-source-firmware-validation/issues/200)

Added test to verify if network boot uses https:// and not http://

---

lib/docks.robot

add tabs before the comment, so that it doesn't get taken for a part of the preceding string

lib/docks.robot: fix Genesys hub comment

---

dasharo-compatibility/reset-to-defaults.robot

Skip tests depending whether individual option is supported instead of whole menu.
After merging #318 those tests would fail on QEMU.

Make "Skip If" more precise in reset-to-defaults.robot

---

platform-configs/include/protectli-v1x10.robot

No USB settings in `Dasharo System Features` on Protectli  v1x10

platform-configs: protectli-v1x10: USB stack/menu not supported

---

dasharo-compatibility/usb-boot.robot
dasharo-compatibility/usb-detect.robot

PR removes non existing keywords and fixes `Enter Tianocore And Return Menu` keyword.
Also test to check if test should fail was moved inside try/except block to Fail test immediately when number of failed tries goes above some threshold (no need to wait for 5 fails if test would fail anyway after first one)
Related to https://github.com/Dasharo/open-source-firmware-validation/pull/312

Fix usb-detect tests

---

keywords.robot

Change deprecated way of using sensors-detect program in linux. calling `yes | sudo sensors-detect` produces a warning:
```
***************************************************************
Warning: the preferred way to run this script non-interactively
is with option --auto. Other methods are discouraged and may
stop working at some point in the future.
***************************************************************
```

Sensors detect deprecated usage

---

lib/secure-boot-lib.robot

Maybe kwd should also be moved to another file, e.g. `menus.robot` as it doesn't really have anything to do with `Secure Boot`?

secure-boot-lib: Fix 'Enter UEFI Shell' documentation

---

dasharo-performance/cpu-temperature.robot

Fixes for https://github.com/Dasharo/open-source-firmware-validation/issues/281

Temperature detection and reporting improvements

---

README.md
dasharo-compatibility/auto-boot-time-out.robot
dasharo-compatibility/dmidecode.robot
dasharo-compatibility/network-boot.robot
dasharo-compatibility/usb-hid-and-msc-support.robot
dasharo-compatibility/wifi-bluetooth-support.robot
dasharo-performance/platform-stability.robot
dasharo-security/tpm-support.robot
scripts/lib/robot.sh
scripts/run.sh
scripts/test.sh

Add tags for minimum regression and make it possible to use tags and any other options of robot from the `scripts/run.sh` wrapper

30B add tags to tests for minimum regression test scope

---

.codespellx
README.md
dasharo-security/measured-boot.robot
lib/bios/menus.robot
lib/tpm.robot
lib/trenchboot.robot
platform-configs/include/default.robot
platform-configs/include/pcengines.robot
platform-configs/qemu.robot
scripts/check-unused-variables.sh
scripts/ci/qemu-run.sh
trenchboot/01-without-drtm.robot
trenchboot/02-with-drtm.robot

So far run it in Qemu which doesn't allow testing of DRTM, but most of test cases do pass.
Start Qemu:
HDD_PATH=tb-minimal-image-genericx86-64.rootfs.wic scripts/ci/qemu-run.sh graphic os
Run tests:
CONFIG=qemu RTE_IP=127.0.0.1 SNIPEIT_NO=1 scripts/run.sh trenchboot
***
Questionable things:
- update `scripts/stats.py`?
- add module to `README.md`? it's not strictly a Dasharo module
***
Currently the new tests won't completely pass anywhere, so maybe this shouldn't be merged until this changes.

Add trenchboot tests

---

dasharo-compatibility/efibootmgr.robot
platform-configs/include/default.robot

Disable for all platforms by default until bricking issue is resolved.

Add flag for efibootmgr tests

---

scripts/lib/robot.sh

In theory using [[]] and * matching should work as expected, that is clear the _robot_args variable if `--` substring was not found in the args. When there is no `--` seperating test suite names from additonal args fails.
In practice it turned out that the condition was always true.  Using grep is using a cannon to kill a fly, but it works.
Bug was merged with this PR:
https://github.com/Dasharo/open-source-firmware-validation/pull/420/files

lib/robot.sh: Fix faulty condition

---

dasharo-compatibility/nvidia.robot

This change makes the automatic test pass when vga controller is detected
Moved from https://github.com/Dasharo/open-source-firmware-validation/pull/466 because of typo in branch name pushed by me because I forgot to install pre-commit

Compatibility nvidia accept vga controller as gpu

---

dasharo-performance/cpu-temperature.robot

Initially the number of temp measurements was equal to TEMPERATURE_TEST_DURATION, but now the time between measurements can be adjusted and calculating the average temperature will fail if the TEMPERATURE_TEST_MEASURE_INTERVAL is not equal to 1

Cpu temp fix calculating mean 

---

scripts/lib/robot.sh

Due this little check missing tests would sometimes be performed twice. The loop would just run from idx=-1 and treat everything as an additional argument to `robot`

scripts/lib/robot.sh: Check if _separator_idx is positive

---

platform-configs/novacustom-v540tnd.robot
platform-configs/novacustom-v560tnd.robot
platform-configs/novacustom-v560tne.robot

In some niche cases (Ubuntu, AC/USB-PD connected, cpu under high load) the CPU clocks can fall down to 200MHz.

platform-configs/novacustom-v5x0tnx: Decrease min cpu clock to 200MHz

---

lib/sleep-lib.robot

If the device takes longer than the time given to the command it will not wake up ever.
This change will increase the time it takes to perform this time every time. Even if the shutdown took only 1s the device will power on only after the specified time.
I don't have a good idea how to solve this unreliability other than increasing the delay...

Increase rtcwake warmboot wait time

---

lib/options/dcu.robot

Fix to: https://github.com/Dasharo/open-source-firmware-validation/issues/524

lib/options/dcu.robot: Change dcu lib to use containered version

---

dasharo-compatibility/memory-profile.robot
lib/bios/menus.robot

"Get Option State" Keyword returns True/False if the value is a boolean value you "check" or "uncheck" and String if there is some text inside. Relying on the type of returned value may be dangerous and it caused the memory-profile test suite to fail because of type errors. 
But the memory profile is a list of values, not a checkbox! Now it turns out if an option value starts with an "X" it is treated as a boolean because the letter "X" is used as a checkmark. That is the case with options like "XMP#1...".

memory-profile.robot: type errors

---

dasharo-compatibility/custom-network-boot-entries.robot

Restore, commented out probably by mistake

custom-network-boot-entries.md: Restore skip if not supported

---

scripts/secure-boot/generate-images/generate-image.sh

This PR solves bugs reported in in issues https://github.com/Dasharo/open-source-firmware-validation/issues/256, https://github.com/Dasharo/open-source-firmware-validation/issues/254 and https://github.com/Dasharo/open-source-firmware-validation/issues/255.
IMHO, if we want the script to be supported on several distros - it is better to use smth like Docker container, so to ommit problems with packages naming and versions.

Fix issues 254 255 256

---

dasharo-compatibility/dmidecode.robot

All of the test cases get some line from output of dmidecode and compare it against the value from platform config. There's no need to do a clean boot between them. Move the common parts of all test cases to the suite setup. In case of MSI Z790-P with two tests skipped, this reduces total suite time by a factor of 8.
Before:
After:

dasharo-compatibility/dmidecode.robot: don't reboot for each test

---

README.md

Improve the tutorial for walkingh through generating the .html documentation for keywords.
Main changes:
- Add a reminder about virtual environment.
- Simplify commands for generating the documentation.

README.md: improve docs gen tutorial

---

lib/bios/menus.robot
lib/trenchboot.robot
platform-configs/include/default.robot
scripts/run.sh
trenchboot/02-with-drtm.robot
trenchboot/README.md

Previously only non-DRTM case was tested, now DRTM one works as well.  It requires SeaBIOS which is harder to automate, see README file for how to use it.
See commit messages for more info.

TrenchBoot updates

---

dasharo-compatibility/usb-hid-and-msc-support.robot
keywords.robot
lib/flash.robot
lib/options/dcu.robot
platform-configs/novacustom-v560tnd.robot
platform-configs/novacustom-v560tne.robot

fix usb-hid-and-msc-support tests missing skip
if tests in firmware not supported

v560tne-v0.9.1-rc3-testing-fixes

---

scripts/lib/robot.sh

Will make it much easier to follow the tests as looking for the file before the tests end and the path is printed is a bit troublesome.

scripts/lib/robot.sh: Print the path of debug log

---

dasharo-compatibility/network-boot-utilities.robot

The NBT test suite is only used on Protectli devices which use a custom network boot menu. Other Dasharo releases should be tested with the PXE test suite. The suites are incompatible and will never both work on one release. This fact is not documented in the tests and may cause confusion and/or errors during release tests.

dasharo-compatibility/network-boot*: Add suite docs

---

keywords.robot
platform-configs/include/default.robot
platform-configs/include/msi-z690-common.robot
platform-configs/include/optiplex-common.robot
platform-configs/include/pcengines.robot
platform-configs/include/protectli-common.robot
platform-configs/include/protectli-v1x10.robot
platform-configs/include/protectli-vp24xx.robot
platform-configs/include/protectli-vp32xx.robot
platform-configs/include/protectli-vp46xx.robot
platform-configs/include/protectli-vp66xx.robot
platform-configs/minnowboard-turbot.robot
platform-configs/odroid-h4-plus.robot
platform-configs/protectli-vp2410.robot
requirements.txt

* Use Power Supply keywords from osfv_cli libs
* Unify Power On keywords in include/default.robot in a for of "Power On Default" keyword, as most of them looked more or less identical
* Platfom configs can choose to use this keyword as Powe On, or define platform-specific one as before
Tested following platforms via the
BPS001.001 from util/basic-platform-setup.robot:
- protectli-vp2410
- protectli-vp2420
- protectli-vp4630
- protectli-vp4670
- protectli-vp6670
- pcengines-apu2
- msi-pro-z690-a-ddr5
- odroid-h4-plus
- minnowboard-turbot
- optiplex-7010

unify approach to Power On

---

platform-configs/include/novacustom-common.robot

https://github.com/Dasharo/open-source-firmware-validation/issues/336
NovaCustom laptops should not support it - change configs
The test may be faulty - look into that

Custom fan curve test fails

---

requirements.txt

Previous PR (couldn't reopen): https://github.com/Dasharo/open-source-firmware-validation/pull/597
Works with: 
```
telnetlib @ git+https://github.com/3mdeb/telnetlib@b85e3b5e6068eb3441cb21badb5a266301839e61
```
Should probably also work with <https://pypi.org/project/telnetlib-313-and-up/>
Quick test:
```
robot -L TRACE -v config:qemu -v rte_ip:127.0.0.1 -v snipeit:no dasharo-compatibility/network-boot.robot
==============================================================================
Network-Boot
==============================================================================
PXE001.001 Dasharo Network Boot is available :: This test aims to ... | PASS |
------------------------------------------------------------------------------
PXE002.001 Dasharo network boot menu boot options order …
```

requirements.txt: update dependencies so they work with Python 3.13
