keys-and-keywords/setup-keywords.robot, platform-configs/msi-pro-z690-a-ddr5.robot, platform-configs/msi-pro-z690-a-wifi-ddr4.robot
Signed-off-by: Kamil Pokornicki <kamil.pokornicki@3mdeb.com>
=> Update rtectrl-rest-api submodule

LICENSE
Signed-off-by: Przemyslaw Sulewski <przemyslaw.sulewski@3mdeb.com>
=> LICENSE: add license file

LICENSE, NOTICE
The NOTICE file is based on guidelines in:
https://infra.apache.org/licensing-howto.html#example-notice
=> LICENSE: relicense to Apache 2.0

.robotidy, dasharo-compatibility/audio-subsystem.robot, dasharo-compatibility/cpu-status.robot, dasharo-compatibility/display-ports-and-lcd-support.robot, dasharo-compatibility/efi.robot, dasharo-compatibility/nvme-support.robot, dasharo-compatibility/usb-hid-and-msc-support.robot, dasharo-compatibility/wifi-bluetooth-support.robot, dasharo-performance/cpu-frequency.robot, dasharo-performance/platform-stability.robot, dasharo-security/secure-boot.robot, dasharo-security/tpm-support.robot, keywords.robot, lib/sd-wire.robot
=> Workaround for Windows Recovery Mode

.codespellx, .github/workflows/qemu-self-test.yml, README.md, os-config/ubuntu-credentials.robot, regression-qemu.sh, scripts/ci/qemu-run.sh, self-tests/dasharo-system-features-menus.robot, self-tests/setup-and-boot-menus.robot
Tested with Ubuntu 22.04.03 installer, manual installation.
OvmgPkg from: https://github.com/Dasharo/edk2/pull/111
Was able to boot with SB enabled.
Without that, installer could not boot at all and/or performed very poorly.
=> Qemu install os

dasharo-compatibility/platform-suspend-and-resume.robot, dasharo-compatibility/usb-type-c.robot, dasharo-stability/m2-wifi.robot, dasharo-stability/network-interface-after-suspend.robot, dasharo-stability/nvme-detection.robot, dasharo-stability/usb-type-a-devices-detection.robot, keywords.robot, lib/bios/menus.robot, lib/sleep-lib.robot, platform-configs/novacustom-nv41pz.robot, regression-novacustom.sh
d3fc1a68cac1f1521b02af9aea80c8a2a43fa47e will add workaround for https://github.com/Dasharo/open-source-firmware-validation/issues/129
=> Sleep tests update for S3 and S0ix

dasharo-compatibility/eMMC-support.robot, keywords.robot, platform-configs/protectli-v1210.robot, platform-configs/protectli-v1410.robot, platform-configs/protectli-v1610.robot, platform-configs/protectli-vp2410.robot, platform-configs/protectli-vp2420.robot, platform-configs/protectli-vp4630.robot, platform-configs/protectli-vp4650.robot, platform-configs/protectli-vp4670.robot
Fixes: https://github.com/Dasharo/dasharo-issues/issues/609
=> dasharo-compatibility/eMMC-support.robot: do not rely on partition table

dasharo-security/secure-boot.robot, lib/secure-boot-lib.robot
This PR adds a test which tests the enrolling of an intermediate key.
=> Intermediate cert test

dasharo-security/secure-boot.robot, lib/secure-boot-lib.robot
and file signing from inside operating system using sbctl
=> dasharo-security/secure-boot.robot: Add test for key enrollment

README.md, ansible-roles/hosts, ansible-roles/os/ubuntu/test.yml, dasharo-security/secure-boot.robot, keywords.robot, lib/QemuMonitor.py, lib/ansible.robot, requirements.txt, variables.robot
Provides possibility to run ansible playbooks on targets using SSH connection
=> Adds possibility to run ansible playbooks on target

dasharo-compatibility/dcu.robot, lib/bios/menus.robot, lib/dmidecode-lib.robot, lib/terminal.robot, platform-configs/include/default.robot, platform-configs/include/msi-z690-common.robot, platform-configs/include/protectli-common.robot, requirements.txt
Protectli VP4670 v2:
```
==============================================================================
Dcu                                                                           
==============================================================================
DCU001.001 Change the UUID :: This test case verifies that the UUI... | PASS |
------------------------------------------------------------------------------
DCU002.001 Change the serial number :: This test case verifies tha... | PASS |
------------------------------------------------------------------------------
DCU003.001 Change the bootsplash logo :: This test case verifies t... | PASS |
------------------------------------------------------------------------------
DCU004.001 Verify SMMSTORE changes :: This test case verifies …
```
=> Dcu test develop v2

dasharo-performance/boot-time-measure.robot, dasharo-performance/cpu-frequency.robot, dasharo-performance/platform-stability.robot, lib/CPU-performance-lib.robot, platform-configs/include/pcengines.robot, platform-configs/msi-pro-z690-a-ddr5.robot, platform-configs/msi-pro-z690-a-wifi-ddr4.robot, platform-configs/msi-pro-z790-p.robot, platform-configs/novacustom-ns50mu.robot, platform-configs/novacustom-ns50pu.robot, platform-configs/novacustom-ns70mu.robot, platform-configs/novacustom-ns70pu.robot, platform-configs/novacustom-nv41mb.robot, platform-configs/novacustom-nv41mz.robot, platform-configs/novacustom-nv41pz.robot, platform-configs/protectli-vp2410.robot, platform-configs/protectli-vp2420.robot, platform-configs/protectli-vp4630.robot, platform-configs/protectli-vp4650.robot, platform-configs/protectli-vp4670.robot
We still need to take a look at:
=> Vp2420 fixes

dasharo-compatibility/esp-scanning.robot
adresses [this issue](https://github.com/Dasharo/open-source-firmware-validation/issues/224)
=> Esp non block test

dasharo-compatibility/nvidia.robot, dasharo-compatibility/usb-hid-and-msc-support.robot, dasharo-security/camera-switch.robot, dasharo-security/wifi-bluetooth-switch.robot, platform-configs/include/protectli-v1x10.robot
Added detection and installation of packets: 'lspci', 'lsusb' or 'fwts' where it was missing.
Fixes: [https://github.com/Dasharo/open-source-firmware-validation/issues/195](https://github.com/Dasharo/open-source-firmware-validation/issues/195)
=> Added detection and installation of missing packets

README.md, platform-configs/include/novacustom-mtl.robot, platform-configs/novacustom-v540tnd.robot, platform-configs/novacustom-v540tu.robot, platform-configs/novacustom-v560tnd.robot, platform-configs/novacustom-v560tne.robot, platform-configs/novacustom-v560tu.robot, variables.robot
README.md: added platforms to the list
variables.robot: added platform configs
=> platform-configs/: added MTL platform configs

assessment/txe-secure-boot.robot, lib/secure-boot-lib.robot, lib/terminal.robot, scripts/ci/qemu-self-test.sh, self-tests/terminal.robot
[https://jira-3mdeb.atlassian.net/browse/PROT-1302](url)
=> 265 execute command in terminal not working in uefi shell

dasharo-performance/cpu-temperature.robot, lib/linux.robot, platform-configs/include/default.robot, platform-configs/include/novacustom-common.robot, platform-configs/include/protectli-common.robot, platform-configs/raptor-cs_talos2.robot, platform-configs/rpi-3b.robot
Not run-time tested yet, because our 6670's are currently checked out.
=> Detect average temperature in CPU tests

dasharo-compatibility/network-boot.robot
Fix for https://github.com/Dasharo/open-source-firmware-validation/issues/321:
=> PXE004.001: removed check for install/update

dasharo-compatibility/custom-network-boot-entries.robot, dasharo-compatibility/efibootmgr.robot, lib/options/dcu.robot, lib/options/uefi-setup-menu.robot
Moved all relevant commits from #340 to a new pull request
=> 32H automate efi boot manager tests

keywords.robot
this change will guide and inform the QA engineer about the 'telnet connection closed' error and how to deal with it
=> Telnet connection error handler

dasharo-compatibility/usb-hid-and-msc-support.robot, variables.robot
Previous PR: https://github.com/Dasharo/open-source-firmware-validation/pull/310
=> Detect keyboard in fw

lib/dts-lib.robot
On laptops `Read From Terminal Until    Enter an option:` should fail in 20 seconds and then try to blindly start ssh server and connect via ssh.
On other platforms keyword should succeed much faster.
Not sure if waiting 20 seconds is ok, too long or too short
=> lib: dts-lib.robot: Fix Boot Dasharo Tools Suite keyword failures on laptops

trenchboot/01-without-drtm.robot, trenchboot/02-with-drtm.robot, variables.robot
@EduKav1813 As you are running these tests currently please say if those changes worked. And maybe post console output after running tests.
=> trenchboot: remove sonoff-api and rtectrl inclusion

lib/me.robot
finding solution for https://github.com/Dasharo/open-source-firmware-validation/issues/364
=> Disabled me fix

variables.robot
aim to resolve this issue:
https://github.com/Dasharo/open-source-firmware-validation/issues/623
=> variables.robot: add vp3210 config
